packages:
  - apps/**
  - "!apps/**/.open-next/**"
  - "!apps/**/.next/**"
  - frontend
  - packages/**
  - infra/**
  - e2e-tests

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
