---
packages:
  - apps/*
  - apps/frontend/web-next
  - apps/frontend/auth
  - packages/**
  - infra/**
  - e2e-tests

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
