name: web-app-react CI

on:
  pull_request:
    branches: [ dev ]
    paths: [ 'src/web-app-react/**' ]
  push:
    branches: [ dev ]
    paths: [ 'src/web-app-react/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: src/web-app-react

    steps:
      - name: Checkout
        uses: actions/checkout@v4

     
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

    
      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate
          pnpm -v

      
      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/web-app-react/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build